project:
  type: website
  output-dir: docs

website:
  title: "Irvin Rojas"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - publications.qmd
      - research.qmd
      - media.qmd
      - about.qmd
      - contact.qmd
  page-footer:
    left: "© 2026 Irvin Rojas"
    center: "Profesor-investigador · División de Economía, CIDE"
    right: "Construido con [Quarto](https://quarto.org){target=\"_blank\"}"


format:
  html:
    theme:
      dark: cyborg
      light: cosmo
    css: styles.css
    toc: true
    page-layout: full


