project:
  type: website
  output-dir: docs

website:
  title: "Irvin Rojas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - publications.qmd
      - research.qmd
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full


