---
title: "Publicaciones"
lang: es
---

## Artículos de investigación

Cassar, A., A. Hobbs, J. Anttila-Hughes, F. Bogliacino, T. J. Lybbert, I. Rojas, K. Mashisia Shikuku, J. Chetwynd, J. Cosgrove, A. Courtman, A. Hall, S. Hermoso, S. Klaus, A. Sottile, \& N. Tkachenko. (2026). ["Gender and Culture Shape Prosociality More than Heat Stress in a Five-Country Experiment."](https://academic.oup.com/pnasnexus/article/5/3/pgag017/8510566){target="_blank"} *PNAS Nexus*, 5 (3), pgag017.

<details class="abstract"><summary>Resumen</summary>
<p>A consistent finding regarding human societies is that higher temperatures lead to antisocial behavior, including more crime, violence, aggression, and civil conflict. A large body of research documents this relationship at the societal level, but an understanding of the psychological and physiological mechanisms underpinning the effect of heat on antisocial behavior remains less understood. We present an experiment designed to isolate the impact of elevated temperatures on social preferences, namely egalitarianism, welfare maximization, selfishness, spite, and competitiveness. We exogenously varied temperatures across lab sessions in five countries in which randomly matched participants make incentivized distributional choices to others and decide whether to compete in a tournament. As an additional manipulation, we include a psychological stressor to potentially trigger an antisocial response when combined with higher temperatures. Our sessions were carried out with university student participants in Colombia, India, Kenya, Mexico, and the United States (N = 1,636). We find that despite a strong negative effect on mood, elevated temperatures had little or no effect on social and economic preferences across countries, especially in comparison to the substantial and significant correlations we find with gender and culture. Future research should more closely examine the alternative channels through which elevated temperatures negatively impact social behavior.</p>
</details>

Rivas, A., Chávez, E., Rojas, I., \& Zaragoza, A. (2025). ["The legal and real incidence of VAT Reforms in Mexico: Distributional effects and impacts on poverty."](https://www.sciencedirect.com/science/article/abs/pii/S0165176525000734){target="_blank"} *Economics Letters*, 248, 112236.

<details class="abstract"><summary>Resumen</summary>
<p>This paper studies the price effects of two asymmetric value-added tax (VAT) reforms in Mexico: a 2014 VAT hike and a 2021 VAT cut implemented in the southern border region. Our estimates show that consumers pay for 25 percent of the VAT change in both reforms, but consumer incidence differs across goods. With the price effect estimates (real incidence), we determine the impact of the VAT reforms on income distribution and poverty. We compare these impacts with the full passthrough of the VAT on prices (legal incidence). Depending on the type of price incidence, the VAT is allocated differently along the income distribution, and the impacts on poverty can vary considerably.</p>
</details>

Ponciano, P. P., \& Rojas, I. (2025). ["Sembrando Vida: An Impact Evaluation on Forest Cover."](https://sobremexico-revista.ibero.mx/index.php/Revista_Sobre_Mexico/article/view/161){target="_blank"} *Sobre México. Revista de Economía*, 1 (11), 80-130.

<details class="abstract"><summary>Resumen</summary>
<p>Abordar los problemas interrelacionados entre la pérdida de biodiversidad y la pobreza requiere un enfoque integral e integrado de políticas. El programa federal Sembrando Vida (SV) en México busca abordar ambos desafíos mediante la implementación de medidas para restaurar la cobertura forestal y aliviar la pobreza. Sin embargo, carece de indicadores sólidos y evaluaciones de impacto, lo que dificulta una comprensión completa de su efectividad. Este estudio busca estimar el impacto del programa en la cobertura forestal al nivel municipal en Chiapas, utilizando imágenes satelitales y datos administrativos en conjunto con metodologías cuasiexperimentales. Como resultado, se identifica que el impacto promedio al nivel municipal oscila entre -1166 y -1524 ha de forma consistente para las diversas definiciones de penetración de SV.</p>
</details>

Rojas, I., \& Schaefer, K. A. (2024). ["Expanding the phytosanitary exclusion zone for Mexican avocados: Market impacts and unintended consequences."](https://www.sciencedirect.com/science/article/pii/S0306919224001490){target="_blank"} *Food Policy*, 129, 102738.

<details class="abstract"><summary>Resumen</summary>
<p>Due to phytosanitary concerns, the U.S. has historically only allowed the importation of avocados from one Mexican state—Michoacán. In Michoacán, avocados have become a source of cartel conflict and violence. In August 2022, authorized shipments of avocados from an additional Mexican state – Jalisco – were allowed to enter the U.S. This research investigates the market impacts and unintended consequences of expanding the phytosanitary exclusion zone for Mexican avocados. We find that expansion of the phytosanitary exclusion zone was unequivocally beneficial from the perspective of U.S. avocado users and consumers. However, economic outcomes in the Mexican market are more nuanced, and temporal relationships suggest expansion of the phytosanitary exclusion zone may have affected cartel-related activity both in Michoacán and Jalisco.</p>
</details>

Angelucci, Manuela, Carlos Chiapa, Silvia Prina, \& Irvin Rojas. (2024). ["Transitory Income Changes and Consumption Smoothing: Evidence from Mexico."](https://www.sciencedirect.com/science/article/abs/pii/S0047272723001950){target="_blank"} *Journal of Public Economics*, 230, 105013.

<details class="abstract"><summary>Resumen</summary>
<p>We test if 3534 beneficiaries of PROSPERA, Mexico's cash transfer program, smooth food consumption before and after the date of the transfer receipt, and if consumption smoothing is costly. The transfer is an anticipated and transitory income shock and, thus, the PIH predicts that consumption should be smooth before and after its receipt. We find that food consumption does not change the days before and after the transfer date and we find no evidence that households bear costs to smooth consumption. The transfer's cost of access, which encompasses participants' distaste for using debit cards and costly ATM withdrawals, may help time-inconsistent and less experienced debit card holders smooth consumption.</p>
</details>

Di Giannatale, S., Díaz, D. F., \& Rojas, I. (2024). "Financial inclusion and vulnerability in Mexico: An analysis of access and resilience." *Development Finance Agenda (DEFA)*, 9 (6), 16-18.

<details class="abstract"><summary>Resumen</summary>
<p>Financial inclusion and economic resilience are key factors in household stability and well-being. In Mexico, while there has been progress in providing access to financial services, a significant portion of the population remains financially vulnerable. This article explores trends in financial inclusion, focusing on access to savings and credit, and examines how these factors affect households' ability to handle financial shocks. Using data from the National Financial Inclusion Survey (ENIF) of 2018 and 2021, we analyze how improvements in financial inclusion have impacted household resilience, with implications for policymakers.</p>
</details>

Berdegué, J. A., Castillo, M. J., Gómez, I., Gordillo, G., Navea, J., Rojas, I., \& Yáñez, R. (2024). ["The importance of assets for coping with COVID-19 and other shocks."](https://www.sciencedirect.com/science/article/pii/S2211912423000627){target="_blank"} *Global Food Security*, 40, 100732.

<details class="abstract"><summary>Resumen</summary>
<p>Rural households in Chile, Colombia, Ecuador, Guatemala and Mexico experienced a series of shocks beginning in 2020, including the COVID-19 pandemic, unemployment, loss of income, an abrupt increase in food prices, hurricanes, a public safety crisis and political instability. Through household surveys in 10 territories in those countries, along with interviews and focus groups, we studied the association between the context created by those shocks, food security and households' coping strategies. The main finding is that the relative level of wealth, measured by households' asset endowment, is the factor that most influences both food insecurity and the strategies households choose for coping with shocks.</p>
</details>

Rojas, Irvin \& Yu, Jisang. (2024). ["A Pandemic Crossing the Border: The Impact of COVID-19 in the US on the Mexican Labor Market."](https://www.journals.uchicago.edu/doi/10.1086/727047){target="_blank"} *Economic Development and Cultural Change*, 73 (1), 195-219.

<details class="abstract"><summary>Resumen</summary>
<p>The US and Mexican labor markets are closely linked through migrant workers and remittances, and changes in remittance flow may alter labor allocations in the origin households. In this paper, we investigate how the prevalence of COVID-19 in the United States affected the local labor market in Mexico. We construct a Mexican municipality-level measure of exposure to COVID-19 in the United States using data on COVID-19 prevalence across the country and data on migrants' destinations in various states. We find a positive effect of COVID-19 exposure in the United States on hours worked among workers in Mexico, yet no significant effects were found for local wages. We also find that the effect varies across subgroups, which indicates that the responses in hours worked depend on household dynamics, the nature of the occupation-specific tasks, and migration intensity. Finally, we document the potential mechanism behind the effect on hours worked, that is, through the changes in remittances sent to the origin municipalities in Mexico.</p>
</details>

Díaz, D. F., Di Giannatale, S., \& Rojas, I. (2023). ["Financial vulnerability and financial instruments: evidence from Mexico."](https://sobremexico-revista.ibero.mx/index.php/Revista_Sobre_Mexico/article/view/133){target="_blank"} *Sobre México Temas de Economía*, 1 (8), 94-134.

<details class="abstract"><summary>Resumen</summary>
<p>En este estudio se realiza un análisis empírico para evaluar el efecto de la posesión de instrumentos financieros, como contratos de ahorro y crédito, en la vulnerabilidad financiera de los hogares. La vulnerabilidad financiera se refiere a la capacidad de los hogares para hacer frente a choques económicos adversos y cumplir con sus pagos regulares de manera puntual. Se utilizan datos de la Encuesta Nacional de Inclusión Financiera para México, edición 2018, para construir un índice de vulnerabilidad financiera y realizar un análisis de "propensity score matching" para estimar el efecto de tener instrumentos financieros en la vulnerabilidad financiera. Nuestros resultados indican que la posesión de instrumentos de ahorro, tanto formales como informales, y de crédito formal, reduce la vulnerabilidad financiera. Sin embargo, también encontramos que contar con crédito informal aumenta la vulnerabilidad financiera.</p>
</details>

Rojas Valdés, Rubén Irvin, Bruce Wydick, \& Travis J. Lybbert. (2021). ["Can Hope Elevate Microfinance? Evidence from Oaxaca Mexico."](https://academic.oup.com/oep/article-abstract/74/1/236/6154385){target="_blank"} *Oxford Economic Papers*, 74 (1), 236-264.

<details class="abstract"><summary>Resumen</summary>
<p>Recent evidence suggests that the average effects of microfinance on borrowers is more modest than previously claimed. We carry out an experiment to test whether an intervention designed to increase aspirational hope among borrowers can elevate microfinance impacts. In collaboration with a microfinance lender in Mexico, we produced a documentary featuring successful borrowers within the organization and designed and implemented a hope curriculum rooted in positive psychology (Snyder, 1994), which conceptualizes hope as aspirations, agency, and pathways. Bank officers incorporated this curriculum into their regular weekly meetings with a randomly treated half of 52 women's savings and credit groups with 733 women over the course of one year. We find that the intervention modestly increased indices measuring both aspirational hope and microenterprise performance over this time period. The intervention significantly increased employment and plans to hire new employees. Increases in microenterprise sales and profits were positive but statistically insignificant.</p>
</details>

Rojas, Irvin. (2021). ["The economic benefits and costs of Covid-19 mitigation measures in Mexico."](https://estudioseconomicos.colmex.mx/index.php/economicos/article/view/415){target="_blank"} *Estudios Económicos*, 36 (1), 27-56.

<details class="abstract"><summary>Resumen</summary>
<p>In this paper I calculate the daily flows of COVID-19 cases under the scenario of social distance and restricted economic activity implemented during the first months after the beginning of the epidemic, and under a counterfactual uncontrolled scenario with no mitigation measures. I estimate that social distance policies reduce the number of COVID-19 cases by 33%, saving over 292,000 lives. The benefits of these measures are monetized as 526 billion USD. Under a plausible economic recovery trajectory, I estimate that the net cost of mitigation in terms of output gap is equal to 35% of Mexico's 2019 GDP.</p>
</details>

Rojas Valdés, R.I. (2021). ["Evaluación de la Efectividad de las Medidas de Mitigación para Aplanar la Curva Epidémica de la COVID-19: Evidencia de Cinco Ciudades de México."](https://denarius.izt.uam.mx/index.php/denarius/article/view/476){target="_blank"} *Denarius*, (40), 21-21.

<details class="abstract"><summary>Resumen</summary>
<p>En promedio, se estima que las medidas de mitigación reducen el número de casos en 46%. Una epidemia de menor magnitud permite una mejor administración de los casos por el sistema de salud al diferir en el tiempo la presión a los recursos de salud. Esto resulta en que el 69% de los fallecimientos que hubieran ocurrido sin medidas de mitigación son evitados por las políticas de distanciamiento social (aproximadamente 129,000 personas). Estos beneficios pueden ser monetizados en cerca de 219 billones de dólares, lo que representa el 8.4% del PIB de México de 2019.</p>
</details>

Hernández, Nataly, \& Rojas, Irvin. (2020). ["Employment Local Multipliers in Mexico."](https://sobremexico-revista.ibero.mx/index.php/Revista_Sobre_Mexico/article/view/43){target="_blank"} *Sobre México Temas de Economía*, (2), 1-33.

<details class="abstract"><summary>Resumen</summary>
<p>En este artículo estimamos el multiplicador local del empleo en el sector comerciable sobre el empleo en el sector no comerciable en México, para el periodo 2000-2010. Usando un estimador de variables instrumentales, nuestros resultados indican que un cambio exógeno de una unidad en el empleo en el sector comerciable genera entre 1.8 y 2.6 empleos adicionales en el sector no comerciable. De estos, entre 1 y 1.5 corresponden al sector formal. Nuestros resultados implican una oportunidad para los hacedores de política que persiguen estrategias de desarrollo, pues la prevalencia de una economía altamente informal se considera frecuentemente un impedimento para el desarrollo económico. Nuestro estudio señala que la creación de empleos en el sector comerciable es una posible estrategia para incrementar el empleo formal en el sector no comerciable. Nuestro análisis también revela que el incremento en el empleo para trabajadores con más de nueve años de educación es dos veces más grande que para aquéllos con menos de nueve años de educación.</p>
</details>

Taylor, J. Edward, Mohamad Alloush, Anubhab Gupta, Rubén Irvin Rojas Valdés, \& Ernesto Gonzalez-Estrada. (2017). ["Economic Life in Refugee Camps."](https://www.sciencedirect.com/science/article/abs/pii/S0305750X17300670){target="_blank"} *World Development*, 95, 334-347.

<details class="abstract"><summary>Resumen</summary>
<p>We analyze economic life in three Congolese refugee camps in Rwanda and the interactions between refugees and local host-country economies within a 10-km radius around each camp. Refugees in one of the three camps received food aid in kind, while in the other two camps they were given cash via cell phones provided by the UN World Food Programme. We find that refugee economies arise inside each camp, and the structure of these economies reflects the economic context around the camps. Despite undergoing forced migration and often living in destitute conditions, refugees actively interact with host country economies. Interactions with the host country result in a divergence of refugee households' income from the assistance they receive. A shift from in-kind to cash aid appears to increase refugee welfare while strengthening market linkages between camp and host economies. This finding is potentially important for refugee policies as well as for other types of development assistance, as donors find themselves under pressure to shift from in-kind to cash aid.</p>
</details>

Rojas Valdés, Rubén Irvin, C.-Y. Cynthia Lin Lawell, \& J. Edward Taylor. (2017). "Migration in Rural Mexico: Strategic Interactions, Dynamic Behavior, and the Environment." *Journal of Academic Perspectives*, 2017 (3).

<details class="abstract"><summary>Resumen</summary>
<p>Understanding international migration is important from both an economic and policy perspective. In this paper, we add to the literature on the determinants of migration by proposing a methodological framework that incorporates strategic interactions and dynamic behavior and use this framework to examine the effects of the environment on migration decisions and welfare. In particular, we apply a structural econometric model of the dynamic game between households in a village making decisions about migration to detailed household-level data from rural Mexico. The structural econometric model enables us to examine how environmental factors, such as changes in precipitation affect the migration decisions of households. We use the parameters we estimate to simulate the effects of counterfactual scenarios regarding climate and the environment on migration decisions and welfare.</p>
</details>

Taylor, J. Edward, Mateusz J. Filipski, Mohamad Alloush, Anubhab Gupta, Rubén Irvin Rojas Valdés, \& Ernesto Gonzalez-Estrada. (2016). ["Economic Impact of Refugees."](https://www.pnas.org/doi/10.1073/pnas.1604566113){target="_blank"} *Proceedings of the National Academy of Sciences*, 113 (27), 7449-7453.

<details class="abstract"><summary>Resumen</summary>
<p>In 2015, the United Nations High Commission for Refugees accommodated over 15 million refugees, mostly in refugee camps in developing countries. The World Food Program provided these refugees with food aid, in cash or in kind. Refugees' impacts on host countries are controversial and little understood. This unique study analyzes the economic impacts of refugees on host-country economies within a 10-km radius of three Congolese refugee camps in Rwanda. Simulations using Monte Carlo methods reveal that cash aid to refugees creates significant positive income spillovers to host-country businesses and households. An additional adult refugee receiving cash aid increases annual real income in the local economy by $205 to $253, significantly more than the $120–$126 in aid each refugee receives. Trade between the local economy and the rest of Rwanda increases by $49 to $55. The impacts are lower for in-kind food aid, a finding relevant to development aid generally.</p>
</details>

Campos-Vázquez, Raymundo M., Andres Hincapie, \& Rubén Irvin Rojas-Valdés. (2012). ["Family Income Inequality and the Role of Married Females' Earnings in Mexico: 1988-2010."](https://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0719-04332012000100003){target="_blank"} *Latin American Journal of Economics -ex Cuadernos de Economia*, 49 (1), 67-98.

<details class="abstract"><summary>Resumen</summary>
<p>We study family income inequality in Mexico from 1988 to 2010, when among married couples, the share of income contributed by females grew from 13 to 23 percent. However, the correlation of married males' to married females' earnings has been fairly stable at 0.28, one of the highest correlations recorded across countries. We follow Cancian and Reed's (1999) methodology in order to determine whether married females' income equalizes total family income distribution. We investigate several counterfactuals and conclude that increased female employment has contributed to a decline in family income inequality through higher married females' labor participation in poor families.</p>
</details>

---

## Capítulos de libro

Rojas, Irvin. (2021). "Trabajo, salarios y relaciones laborales." En Blanca Heredia y Hernán Gómez Bruera (coords.), *4T. Claves para descifrar el rompecabezas*, Grijalbo, Ciudad de México, 249-271.

Rojas Valdés, Rubén Irvin. (2012). "Transmisión Intergeneracional del Ingreso en México." En Raymundo M. Campos Vázquez, Juan E. Huerta Wong \& Roberto Velez Grajales (eds.), *Movilidad Social en México: Constantes de la Desigualdad*, Centro de Estudios Espinosa Yglesias, México, D.F., 299-351.

---
